---
title: "Mixed Models - Simple Repeated Measures"
subtitle: Use emmeans for contrasts (planned comparisons)
output:
  html_document:
    df_print: paged
---
Repeated measures ANOVA; fully balanced where every individual was measured in each of
four seasons. Data are miles moved per season (Animals.jmp).

https://www.jmp.com/support/help/en/15.2/index.shtml#page/jmp/simple-split-plot-or-repeated-measures-model.shtml

```{r load libraries, message=FALSE}
#install.packages("devtools")
#devtools::install_github("easystats/easystats")

library(tidyverse)
library(lme4)
library(lmerTest)
library(emmeans)
library(performance)
```

```{r import data, message=FALSE}
Animals <- read_csv("Animals.csv")
```

```{r summarize data and plot, message=FALSE}
summary <- Animals %>%
  group_by(species, season) %>%
  summarise(n = n(),
           mean_move=mean(miles),
           se_move=sd(miles)/sqrt(n()))
            
summary
```

```{r}
mixed_animals <- lmer(miles~species*season+(1|subject), data = Animals)
#not syntax for model specification:compact syntax
anova(mixed_animals) #gives us tests for fixed effects
```

```{r}
summary(mixed_animals)
```

```{r check model, fig.width=9.5, fig.height=9, message=FALSE}
performance::check_model(mixed_animals) #analogous to autoplot, but for more complex models
```

```{r emmeans}
#calculate model-adjusted means (e.g. estimated marginal means)
mixed_animals_emm <- emmeans(mixed_animals, "season", "species")
mixed_animals_emm
```

```{r emmeans as dataframe}
data_emm <- as.data.frame(summary(mixed_animals_emm))
#data_emm <- as.data.frame(summary(mixed_animals_emm))[c('season', 'species', 'emmean', 'SE')] #specify columns to print
data_emm
#model-adjusted means (emm) are identical to raw means (see above) since nothing really being adjusted in fully balanced experiment.
```

```{r}
#notice that SE is same value for all emmeans: this is expected

#https://www.ibm.com/support/pages/estimated-marginal-means-all-have-same-standard-error-spss#:~:text=Both%20are%20correct%2C%20because%20the,variation%20about%20that%20group's%20mean.&text=The%20model%20is%20that%20each,same%20for%20all%20the%20groups.

#https://stats.stackexchange.com/questions/444707/standard-error-in-estimated-marginal-means-are-all-the-same

#https://github.com/jamovi/jamovi/issues/660
```

```{r plot emmeans}
#relevel factors into intuitive order
data_emm$season <- factor(data_emm$season, levels = c("fall", "winter", "spring", "summer"))

p<- ggplot(data_emm, aes(x=season, y=emmean, group=species, color=species)) + 
  geom_line() +
  geom_point(size=4)+
  geom_errorbar(aes(ymin=emmean-SE, ymax=emmean+SE), width=.2)+
  labs(title="Distance Traveled Per Season (marginal means +/- 1 SE)", x="Season", y = "Distance Traveled (miles)")
p
```
```{r seasonal contrasts BETWEEN species}
pairs(emmeans(mixed_animals, "species", "season"))
```

```{r seasonal contrasts WITHIN species, Tukey adjusted}
pairs(emmeans(mixed_animals, "season", "species"))
#pairs(mixed_animals_emm)
```
```{r all season:species pairwise CONTRASTS}
emmeans(mixed_animals_emm, specs = pairwise ~ season:species)
#probably no a priori reason to use this table, but here it is.
```
